/**
 * PSD2 ASPSP services for AISP, PISP and PIISP.
 * This API intends to provide an interface between - Account Servicing Payment Service Providers (ASPSP) - Third Party (Payment Service) Providers (TPP)  TPP may act with different roles as described below: - Account Information Service Providers (AISP) - Payment Initiation Service Providers (PISP) - Payment Instrument Issuer Service Providers (PIISP)  The Payment Service User (PSU) is the owner of the accounts held by the ASPSP and gives accreditations to the TPP in order to access his accounts information or initiates payment from these accounts  The API is designed on a REST model using JSON structures.  The Richardson Maturity Model is applied on level three using HAL HYPERMEDIA links 
 *
 * OpenAPI spec version: 1.2.2
 * Contact: psd2@stet.eu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * ISO20022: Key elements used to identify the original transaction that is being referred to.  API: Some data must be assigned by the ASPSP after successful processing of the payment activation request 
 */
export interface OriginalTransactionReference {
    Amt: models.AmountTypeChoice;

    /**
     * ISO20022: Date at which the initiating party requests the clearing agent to process the payment. 
     */
    ReqdExctnDt: Date;

    PmtTpInf: models.PaymentTypeInformation;

    PmtMtd: models.PaymentMethodCode;

    RmtInf: models.RemittanceInformation;

    Dbtr: models.PartyIdentification;

    DbtrAgt: models.BranchAndFinancialInstitutionIdentification;

    CdtrAgt: models.BranchAndFinancialInstitutionIdentification;

    Cdtr: models.PartyIdentification;

    CdtrAcct: models.CashAccount;

    UltmtCdtr: models.PartyIdentification;

}
