/**
 * PSD2 ASPSP services for AISP, PISP and PIISP.
 * This API intends to provide an interface between - Account Servicing Payment Service Providers (ASPSP) - Third Party (Payment Service) Providers (TPP)  TPP may act with different roles as described below: - Account Information Service Providers (AISP) - Payment Initiation Service Providers (PISP) - Payment Instrument Issuer Service Providers (PIISP)  The Payment Service User (PSU) is the owner of the accounts held by the ASPSP and gives accreditations to the TPP in order to access his accounts information or initiates payment from these accounts  The API is designed on a REST model using JSON structures.  The Richardson Maturity Model is applied on level three using HAL HYPERMEDIA links 
 *
 * OpenAPI spec version: 1.2.2
 * Contact: psd2@stet.eu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * ISO20022: Underlying reason for the payment transaction.  API: Only <Cd> structure is allowed 
 */
export interface PurposeChoice {
    /**
     * ISO20022: Underlying reason for the payment transaction, as published in an external purpose code list.  API:  - Only the \"COMC\" value is allowed for Payment initiation Request (1-PISP) - 'ACCT' (Funds moved between 2 accounts of same account holder at the same bank) and 'CASH' (general cash management instruction) may be used for Transfer Initiation (R-PISP)  
     */
    Cd: PurposeChoice.CdEnum;

}
export namespace PurposeChoice {
    export     enum CdEnum {
        ACCT = <any> 'ACCT',
        CASH = <any> 'CASH',
        COMC = <any> 'COMC'
    }
}
