/**
 * PSD2 ASPSP services for AISP, PISP and PIISP.
 * This API intends to provide an interface between - Account Servicing Payment Service Providers (ASPSP) - Third Party (Payment Service) Providers (TPP)  TPP may act with different roles as described below: - Account Information Service Providers (AISP) - Payment Initiation Service Providers (PISP) - Payment Instrument Issuer Service Providers (PIISP)  The Payment Service User (PSU) is the owner of the accounts held by the ASPSP and gives accreditations to the TPP in order to access his accounts information or initiates payment from these accounts  The API is designed on a REST model using JSON structures.  The Richardson Maturity Model is applied on level three using HAL HYPERMEDIA links 
 *
 * OpenAPI spec version: 1.2.2
 * Contact: psd2@stet.eu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {GenericLink}  from './GenericLink';

/**
 * links that can be used for further navigation when browsing Account Informations at one account level - parent-list: link to the list of all available accounts - gbal: link to the balances of a given account - self: link to the transactions of a given account - first: link to the first page of the transactions result - last: link to the last page of the transactions result - next: link to the next page of the transactions result - prev: link to the previous page of the transactions result 
 */
export interface TransactionsLinks {
    
    Self: GenericLink;

//    Parent-list?: GenericLink;
//
//    Balances?: GenericLink;
//
//    First?: GenericLink;
//
//    Last?: GenericLink;
//
//    Next?: GenericLink;
//
//    Prev?: GenericLink;

}
